sudo: required
services:
  - docker
before_install:
  - docker build -t sloan58/udemy-docker-laravel . --platform linux/x86_64
script:
  - docker run sloan58/udemy-docker-laravel ./vendor/bin/phpunit
